### ISSUE TITLE
機器人錯誤回報表單 from Programming (844597380170252348)

### ISSUE THREAD

**Issue by BotAutoBugSubmission** [TK-Entertainment/tkablent#10]
**錯誤代碼**  
LEAVEFAIL (機器人嘗試離開頻道時失敗)  
  
**錯誤回報時間**  
2022/06/11 23:09:06 (Taipei Standard Time)  
  
**造成錯誤之影片連結**  
無影片連結可用，或此類錯誤與歌曲播放無關  
  
**使用者回報之簡述**  
owo  
  
**參考錯誤代碼**  
None  
  
**此 Issue 為機器人端表單所開啟的**  
**發出表單機器人: TKablent | LocalDev#9709**  
**機器人版本: master Branch / 本地開發版本**

**Comment by kevin0216** [comment]
無影片連結測試成功。
