### ISSUE TITLE
機器人錯誤回報表單 from 郭297974 的伺服器 (801987418601422858)

### ISSUE THREAD

**Issue by BotAutoBugSubmission** [TK-Entertainment/tkablent#16]
**錯誤代碼**  
JOINFAIL (機器人嘗試加入頻道時失敗)  
  
**錯誤回報時間**  
2022/06/24 13:55:30 (Taipei Standard Time)  
  
**造成錯誤之影片連結**  
無影片連結可用，或此類錯誤與歌曲播放無關  
  
**使用者回報之簡述**  
我打在不是語音頻道的地方 笑死  
  
**參考錯誤代碼**  
'NoneType' object has no attribute 'channel'  
  
**此 Issue 為機器人端表單所開啟的**  
**發出表單機器人: TKablent | Alpha#5914**  
**機器人版本: Alpha or Beta / 測試版本**

**Comment by kevin0216** [comment]
經確認無問題，關閉 issue
