### ISSUE TITLE
機器人錯誤回報表單 from Programming (844597380170252348)

### ISSUE THREAD

**Issue by BotAutoBugSubmission** [TK-Entertainment/tkablent#9]
**錯誤代碼**  
PLAY_NOTSTARTED (播放時，機器人偵測到該影片為尚未開始的直播)  
  
**錯誤回報時間**  
2022/06/11 23:05:14 (Taipei Standard Time)  
  
**造成錯誤之影片連結**  
https://youtube.com/watch?v=kJRUDb7bipM  
  
**使用者回報之簡述**  
owo  
  
**參考錯誤代碼**  
[0;31mERROR:[0m [youtube] kJRUDb7bipM: This live event will begin in 203 days.  
  
**此 Issue 為機器人端表單所開啟的**  
**發出表單機器人: TKablent | LocalDev#9709**  
**機器人版本: master Branch / 本地開發版本**

**Comment by kevin0216** [comment]
機器人表單測試成功
